# Generated by Django 4.0.4 on 2022-05-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_singlepost_post_rename_text_post_first_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='first_text',
            new_name='text',
        ),
    ]
