# Generated by Django 4.0.4 on 2022-05-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('first_time', models.CharField(max_length=200)),
                ('second_time', models.CharField(max_length=200)),
            ],
        ),
    ]
