# Generated by Django 4.0.4 on 2022-05-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_instructors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructors',
            new_name='Instructor',
        ),
    ]
