# Generated by Django 4.0.4 on 2022-05-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_rename_instructors_instructor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructor',
            new_name='Image_row1',
        ),
    ]
