# Generated by Django 4.0.4 on 2022-05-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_vertical_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_row1',
        ),
        migrations.DeleteModel(
            name='Image_row2',
        ),
        migrations.DeleteModel(
            name='Vertical_image',
        ),
    ]
